config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth', registrations: 'users/registrations' }

  root 'books#index'

  resources :books, only: %i[index show] do
    resource :favorites, only: %i[create destroy]
  end

  resources :books, only: [:show] do
    resource :comments
  end

  resources :authors, only: %i[index show]

  resources :lists

  scope module: :books do
    resources :searches, only: %i[index]
  end

  resources :favorites, only: :index
  resources :books_lists, only: %i[create destroy]
  resources :rating_books, only: %i[create destroy]
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  include PublicActivity::Model
  tracked
  tracked owner: proc { |controller| controller&.current_user }

  belongs_to :user

  has_many :books_lists, foreign_key: :list_id, dependent: :destroy
  has_many :books, through: :books_lists, source: :book

  validates :name, presence: true
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :find_list, only: %i[show destroy]

  def index
    @facade = ::Lists::IndexFacade.new(user: current_user)
  end

  def show
    @facade = ::Lists::ShowFacade.new(list: @list)
  end

  def new
    @list = current_user.lists.build
  end

  def create
    @list = current_user.lists.build(list_params)
    if @list.save
      redirect_to user_lists_path, notice: I18n.t('lists.create')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to user_lists_path, alert: I18n.t('lists.delete')
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def find_list
    @list = List.find(params[:id])
  end
end

app/views/lists/index.html.haml
%h2.card-title= t('.lists')
%h4
  .align-center= link_to t('.add_list'), new_list_path
- if @facade.lists.blank?
  %h4
    .align-center= t('.empty')
- else
  - @facade.lists.each do |list|
    .card.mb-2
      .card-body
        .align-center= link_to list.name, list_path(list)
        = link_to t('.delete_list'), list_path(list), method: :delete, data: { confirm: t('.confirmation') }, class: "text-danger"

app/views/lists/new.html.haml
= simple_form_for [current_user, @list], defaults: { input_html: { class: 'mb-2' } } do |f|
  = f.input :name, placeholder: t('.name'), label: t('.add_list')
  = f.button :submit, class: 'btn btn-outline-success mb-2'
  = link_to t('.back'), user_lists_path, class: 'btn btn-outline-secondary btn-sm'

app/views/lists/show.html.haml
%h5.align-center= @facade.list_name
- if @facade.list_books.empty?
  %h6.align-center= t('.empty')
= render "shared/books_card", books: @facade.list_books do |book|
  =  link_to t('.delete'), books_list_path(book_id: book, list_id: @list.id), method: :delete