config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth', registrations: 'users/registrations' }

  root 'books#index'

  resources :books, only: %i[index show] do
    resource :favorites, only: %i[create destroy]
  end

  resources :books, only: [:show] do
    resource :comments
  end

  resources :authors, only: %i[index show]

  resources :lists

  scope module: :books do
    resources :searches, only: %i[index]
  end

  resources :favorites, only: :index
  resources :books_lists, only: %i[create destroy]
  resources :rating_books, only: %i[create destroy]
end

app/views/shared/_book_card.html.haml
.card.text-center.mx-auto.mb-3.style
  - if book.cover.attached?
    = link_to image_tag( book.cover, width: "250pt" ), book_path(book), class: "card-img-top"
  - else
    = link_to image_tag( "NoBookCover.png", width: "250pt" ), book_path(book), class: "card-img-top"
  .card-body
    = book.title
    %br/
    = yield(book) if block_given?

app/views/shared/_books_card.html.haml
.row
  - books.each do |book|
    .card.text-center.mx-auto.mb-3.style
      - if book.cover.attached?
        = link_to image_tag( book.cover, width: "250pt" ), book_path(book), class: "card-img-top"
      - else
        = link_to image_tag( "NoBookCover.png", width: "250pt" ), book_path(book), class: "card-img-top"
      .card-body
        = book.title
        %br/
        = yield(book) if block_given?

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    #navbarNav.collapse.navbar-collapse
      %ul.navbar-nav
        %li.nav-item
          = link_to t('.books'), root_path, class: 'nav-link'
        %li.nav-item
          = link_to t('.authors'), authors_path, class: 'nav-link'
        - if user_signed_in?
          %li.nav-item
            = link_to t('.favorites'), favorites_path, class: 'nav-link'
          %li.nav-item
            = link_to t('.lists'), lists_path, class: 'nav-link'
      %ul.navbar-nav.ms-auto
        - if user_signed_in?
          %li.nav-item
            = link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: 'nav-link'
        - else
          %li.nav-item
            = link_to t('.register'), new_user_registration_path, class: 'nav-link'
          %li.nav-item
            = link_to t('.sign_in'), new_user_session_path, class: 'nav-link'