config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth', registrations: 'users/registrations' }

  root 'books#index'

  resources :books, only: %i[index show] do
    resource :favorites, only: %i[create destroy]
  end

  resources :books, only: [:show] do
    resource :comments
  end

  resources :authors, only: %i[index show]

  resources :lists

  scope module: :books do
    resources :searches, only: %i[index]
  end

  resources :favorites, only: :index
  resources :books_lists, only: %i[create destroy]
  resources :rating_books, only: %i[create destroy]
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  include PublicActivity::Model
  extend Pagy::Searchkick
  tracked owner: proc { |controller| controller&.current_admin_user }

  MIN_DESCRIPTION_LENGTH = 5

  searchkick text_middle: %i[title]
  has_one_attached :cover
  has_and_belongs_to_many :authors
  # books of list
  has_many :books_lists, foreign_key: :book_id, dependent: :destroy
  has_many :books_of_list, through: :books_lists, source: :list
  # favorites of user
  has_many :favorites, foreign_key: :book_id, dependent: :destroy
  has_many :favorites_book, through: :favorites, source: :user

  has_many :rating_books

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true, length: { minimum: MIN_DESCRIPTION_LENGTH }

  enum category: {
    biography: 'biography',
    detective: 'detective',
    fantasy:   'fantasy',
    mystery:   'mystery',
    horror:    'horror',
    other:     'other'
  }
end

app/controllers/books/searches_controller.rb
# frozen_string_literal: true

module Books
  class SearchesController < ApplicationController
    def index
      if params[:search].blank?
        redirect_to root_path
      else
        @results = ::Books::Search.call(search: params[:search])
      end
    end
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :find_book, only: :show

  def index
    @facade = ::Books::IndexFacade.new(
      page:     params[:page],
      category: params[:category]
    )
  end

  def show
    @facade = ::Books::ShowFacade.new(
      book: @book.decorate,
      user: current_user
    )
  end

  private

  def find_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description, :category, :pages_count,
                                 :published_at, :publisher, :cover, author_ids: [])
  end
end

app/views/books/_chart.html.haml
- if user_signed_in?
  .align-center
    - Rating.all.each do |rating|
      - if @facade.book.rated_by?(current_user) && rating.id == RatingBook.find_by(book_id: book, user_id: current_user).rating_id
        = link_to rating.title, rating_book_path(id: book, rating_id: rating), method: :delete, class: "btn btn-success"
      - else
        = link_to rating.title, rating_books_path(id: book, rating_id: rating), method: :post, class: "btn btn-primary"
= pie_chart @facade.book_rating

app/views/books/_favorites.html.haml
.align-center
  %strong= t('.favorite')
  - if !user_signed_in? || !@facade.book.followed_by?(current_user)
    = link_to image_tag('star-empty.jpg', option = {height: '25px'}),
      book_favorites_path(book_id: book), method: :post
  - else
    = link_to image_tag('star.jpg', option = {height: '25px'}),
      book_favorites_path(book_id: book), method: :delete

app/views/books/_list.html.haml
- if user_signed_in?
  - unless current_user.lists.blank?
    - @facade.lists.each do |list|
      - if list.book_in_list?(book)
        = link_to t('.delete_book'), books_list_path(book_id: book, list_id: list.id), method: :delete
        = list.name
        %br/
      - else
        = link_to t('.add_book'), books_lists_path(book_id: book, list_id: list.id), method: :post
        = list.name
        %br/
  %br/

app/views/books/index.html.haml
%h1.card-title= t('.books')
- unless @facade.book_present?
  = t('.nothing')
- else
  .dropdown
    %button#filter-categories.btn.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", type: "button"}
      = t('.categories')
    %ul.dropdown-menu{ "aria-labelledby" => "filter-categories" }
      %li
        = link_to t('.all'), root_path, class: "dropdown-item"
      - @facade.categories.each do |category|
        %li
          = link_to category.first, books_path(category:), class: "dropdown-item"

  = form_tag(searches_path, method: :get) do
    .input-group.mb-2
      = search_field_tag :search, params[:search], placeholder: t('.search_book'), class: 'form-control'
      .input-group-btn
        = button_tag t('.search'), class: 'btn btn-outline-success', name: nil
  = render 'shared/books_card', books: @facade.books
  .align-center
    = pagy_bootstrap_nav(@facade.paginate).html_safe

app/views/books/search.html.haml
%h3= t('.search')
- if @results.blank?
  %strong= t('.search_result_error')
  %br/

.row
  - @results.each do |book|
    = render "shared/book_card", book: book

= link_to t('.back'), root_path, class: 'btn btn-outline-secondary btn-sm'

app/views/books/show.html.haml
= render "books/favorites", book: @facade.book

.card-title.d-flex.justify-content-between
  %div
    %strong= t('.title')
    = @facade.book_title
    %br/
    %strong= t('.description')
    = @facade.book_description
    %br/
    %strong= t('.category')
    = @facade.book_category
    %br/
    %strong= t('.pages')
    = @facade.book_pages_count
    %br/
    %strong= t('.published')
    = @facade.book_published_at
    %br/
    %strong= t('.publisher')
    = @facade.book_publisher
    %br/
    - unless @facade.book_authors.empty?
      %strong= t('.authors')
      - @facade.book_authors.each do |author|
        %ul
          %li= link_to author.full_name, author_path(author)
  %div
    - if @facade.book_cover.attached?
      = image_tag @facade.book_cover, width: "250pt"
    - else
      = image_tag("NoBookCover.png", option = {height: "250pt"})

= render 'books/list', book: @facade.book
= render "books/chart", book: @facade.book
= render 'comments/form', book: @facade.book if user_signed_in?
= render partial: 'comments/content', collection: @facade.list_comments, as: :comment

= link_to t('.back'), root_path